Repository ehpor/hcipy, pull requests merged in 2021-11, with the labels that each got.

#117 Change CI test for thin lens to use FresnelPropagator.
  tests/test_optics.py
Labels: bug

#114 Add the GMT and TMT pupil
  hcipy/aperture/__init__.py
  hcipy/aperture/generic.py
  hcipy/aperture/realistic.py
  tests/baseline_for_apertures/gmt/pupil.fits.gz
  tests/baseline_for_apertures/gmt/pupil_normalized.fits.gz
  tests/baseline_for_apertures/gmt/pupil_normalized_without_spiders.fits.gz
  tests/baseline_for_apertures/gmt/pupil_without_spiders.fits.gz
  tests/baseline_for_apertures/tmt/pupil.fits.gz
  tests/baseline_for_apertures/tmt/pupil_normalized.fits.gz
  tests/baseline_for_apertures/tmt/pupil_normalized_without_spiders.fits.gz
  tests/baseline_for_apertures/tmt/pupil_without_spiders.fits.gz
  tests/test_aperture.py
Labels: enhancement

#115 Autodetect FFTs for make_fourier_transform().
  hcipy/fourier/__init__.py
  hcipy/fourier/fast_fourier_transform.py
  hcipy/fourier/fourier_transform.py
  hcipy/wavefront_sensing/pyramid.py
  tests/test_fourier.py
Labels: bug, enhancement
