Repository ehpor/hcipy, pull requests merged in 2022-08, with the labels that each got.

#130 Temporarily disable the pickle test.
  tests/test_optics.py
Labels: bug, maintenance

#124 Switch to importlib from pkg_resources
  doc/compile_tutorials.py
  doc/conf.py
  doc/development/project_setup.rst
  doc/requirements.txt
  hcipy/config/config.py
  hcipy/config/default_config.yaml
  hcipy/fourier/fast_fourier_transform.py
  hcipy/optics/deformable_mirror.py
  hcipy/optics/glass.py
  hcipy/optics/influence_dm5v2.fits
  hcipy/optics/ohara_glass_catalogue_2019_08.csv
  hcipy/optics/schott_glass_catalogue_2018_09.csv
  hcipy/version.py
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: maintenance

#132 Remove Python 3.6 support. Add 3.10 support.
  azure-pipelines.yml
  setup.py
Labels: maintenance

#135 Fix miscellaneous documentation warnings
  doc/conf.py
  hcipy/fourier/fourier_transform.py
  hcipy/optics/detector.py
Labels: documentation

#133 HabEx and Hubble telescope pupils
  doc/compile_tutorials.py
  doc/tutorial_notebooks/TelescopePupils/TelescopePupils.ipynb
  hcipy/aperture/__init__.py
  hcipy/aperture/realistic.py
  tests/baseline_for_apertures/habex/pupil.fits.gz
  tests/baseline_for_apertures/habex/pupil_normalized.fits.gz
  tests/baseline_for_apertures/hst/pupil.fits.gz
  tests/baseline_for_apertures/hst/pupil_normalized.fits.gz
  tests/baseline_for_apertures/hst/pupil_normalized_without_pads.fits.gz
  tests/baseline_for_apertures/hst/pupil_normalized_without_pads_without_spiders.fits.gz
  tests/baseline_for_apertures/hst/pupil_normalized_without_spiders.fits.gz
  tests/baseline_for_apertures/hst/pupil_without_pads.fits.gz
  tests/baseline_for_apertures/hst/pupil_without_pads_without_spiders.fits.gz
  tests/baseline_for_apertures/hst/pupil_without_spiders.fits.gz
  tests/test_aperture.py
Labels: enhancement, documentation

#137 Bugfix for missing shift during finding best FT method
  hcipy/fourier/fourier_transform.py
  tests/test_fourier.py
Labels: bug

#139 Add the JWST aperture.
  doc/tutorial_notebooks/TelescopePupils/TelescopePupils.ipynb
  hcipy/aperture/__init__.py
  hcipy/aperture/generic.py
  hcipy/aperture/realistic.py
  tests/baseline_for_apertures/jwst/pupil.fits.gz
  tests/baseline_for_apertures/jwst/pupil_without_spiders.fits.gz
  tests/test_aperture.py
Labels: enhancement

#138 Add comparison (equality and inequality) operators to Grids.
  hcipy/field/coordinates.py
  hcipy/field/grid.py
  tests/test_field.py
  tests/test_fourier.py
Labels: enhancement

#146 Pin asdf version for Python 3.7.
  setup.py
Labels: bugfix

#147 Print out the versions for all installed packages.
  azure-pipelines.yml
Labels: maintenance

#143 Fiber shift
  hcipy/optics/fiber.py
Labels: enhancement

#140 Improve aperture performance
  hcipy/aperture/generic.py
  tests/baseline_for_apertures/circular/pupil_large.fits.gz
  tests/baseline_for_apertures/circular/pupil_small.fits.gz
  tests/baseline_for_apertures/rectangular/pupil_elongated.fits.gz
  tests/baseline_for_apertures/rectangular/pupil_square.fits.gz
  tests/test_aperture.py
Labels: enhancement

#149 Change interpolation default for `imshow_field()`
  hcipy/plotting/field.py
Labels: maintenance

#141 Rename existing aperture functions.
  examples/angular_spectrum_propagator.py
  examples/noisy_detector.py
  examples/phase_screens.py
  examples/wavefront_sensor.py
  hcipy/aperture/__init__.py
  hcipy/aperture/generic.py
  hcipy/aperture/realistic.py
  hcipy/coronagraphy/vortex.py
  hcipy/dev.py
  hcipy/mode_basis/disk_harmonic.py
  hcipy/optics/aberration.py
  hcipy/wavefront_sensing/pyramid.py
  hcipy/wavefront_sensing/zernike_wavefront_sensor.py
  tests/test_aperture.py
  tests/test_atmosphere.py
  tests/test_coronagraphy.py
  tests/test_mode_basis.py
  tests/test_optics.py
  tests/test_plotting.py
  tests/test_propagation.py
  tests/test_util.py
  tests/test_wavefront_sensing.py
Labels: enhancement

#150 Fix usage of deprecated function in tests.
  .github/workflows/lint.yml
  hcipy/aperture/generic.py
  hcipy/dev.py
  tests/test_coronagraphy.py
Labels: bugfix

#148 Add changelog for v0.5.0.
  doc/changelog.rst
Labels: documentation
