Repository ehpor/hcipy, pull requests merged in 2023-03, with the labels that each got.

#172 Add missing colon for conda installation
  doc/installation.rst
Labels: documentation, bugfix

#155 Add Keck aperture
  doc/tutorial_notebooks/TelescopePupils/TelescopePupils.ipynb
  hcipy/aperture/__init__.py
  hcipy/aperture/realistic.py
  tests/baseline_for_apertures/keck/pupil.fits.gz
  tests/baseline_for_apertures/keck/pupil_without_segment_gaps.fits.gz
  tests/baseline_for_apertures/keck/pupil_without_spiders.fits.gz
  tests/baseline_for_apertures/keck/pupil_without_spiders_without_segment_gaps.fits.gz
  tests/test_aperture.py
Labels: enhancement

#175 Add problem matcher to annotate flake8 errors in PRs.
  .github/flake8_problem_matcher.json
  .github/workflows/lint.yml
Labels: maintenance, bugfix

#173 Deterministic atmospheric phase screens
  hcipy/atmosphere/atmospheric_model.py
  hcipy/atmosphere/finite_atmospheric_layer.py
  hcipy/atmosphere/infinite_atmospheric_layer.py
  hcipy/util/spectral_noise.py
  tests/test_atmosphere.py
Labels: enhancement, documentation
