Repository ehpor/hcipy, pull requests merged in 2023-11, with the labels that each got.

#199 replace asdf.fits_embed
  hcipy/util/io.py
Labels: bugfix

#206 Fix utcnow() deprecation in Python 3.12.
  hcipy/util/io.py
Labels: maintenance, bugfix

#207 Fix `get_cmap()` deprecation.
  hcipy/plotting/animation.py
  hcipy/plotting/field.py
Labels: maintenance, bugfix

#208 Explicitly use zeroth element of random array.
  tests/test_optics.py
Labels: maintenance, bugfix

#152 Add Keck atmosphere from KAON303
  hcipy/atmosphere/__init__.py
  hcipy/atmosphere/standard_atmosphere.py
Labels: enhancement

#212 Add support for Python 3.11.
  azure-pipelines.yml
  pyproject.toml
Labels: maintenance

#210 Explicitly use v2 of the imageio API.
  hcipy/plotting/animation.py
  tests/test_plotting.py
Labels: maintenance, bugfix

#215 Fix docstring typos
  hcipy/interpolation/linear.py
  hcipy/metrics/profile.py
  hcipy/optics/aberration.py
  hcipy/util/spectral_noise.py
Labels: documentation

#165 Add FQPM coronagraph
  hcipy/coronagraphy/__init__.py
  hcipy/coronagraphy/fqpm.py
  hcipy/coronagraphy/multi_scale.py
  hcipy/coronagraphy/vortex.py
  tests/test_coronagraphy.py
Labels: enhancement
