Repository ehpor/hcipy, pull requests merged in 2023-04, with the labels that each got.

#176 Dispersion optics
  hcipy/optics/__init__.py
  hcipy/optics/dispersion_optics.py
  tests/test_optics.py
Labels: enhancement

#185 Remove codecov from dev requirements.
  setup.py
Labels: maintenance, bugfix

#181 Fourier symmetry tests
  tests/test_fourier.py
Labels: enhancement

#179 Upgrade packaging to `pyproject.toml`.
  .gitignore
  doc/development/new_release.rst
  doc/development/project_setup.rst
  hcipy/__init__.py
  hcipy/util/io.py
  hcipy/version.py
  pyproject.toml
  setup.py
Labels: maintenance

#178 Zoom Fast Fourier Transform and Chirp Z-Transform
  hcipy/fourier/__init__.py
  hcipy/fourier/chirp_z_transform.py
  hcipy/fourier/zoom_fast_fourier_transform.py
  tests/test_fourier.py
Labels: enhancement

#188 FPS changed to duration in imageio dependency
  hcipy/plotting/animation.py
Labels: bugfix

#190 Fix `reset()` for atmospheric layers
  hcipy/atmosphere/finite_atmospheric_layer.py
  hcipy/atmosphere/infinite_atmospheric_layer.py
  tests/test_atmosphere.py
Labels: bugfix
