Repository ehpor/hcipy, pull requests merged in 2025-07, with the labels that each got.

#267 Put test output in temporary directory.
  tests/test_plotting.py
Labels: bugfix

#265 Non-separated grids for segmented apertures.
  hcipy/aperture/generic.py
  tests/test_aperture.py
Labels: bugfix

#266 Fix misc docs issues.
  doc/tutorial_notebooks/ShackHartmannWFS/ShackHartmannWFS.ipynb
  hcipy/fourier/chirp_z_transform.py
  hcipy/plotting/animation.py
  pyproject.toml
Labels: documentation, bugfix

#214 Refactoring standardized atmospheres
  doc/getting_started/3_atmosphere_adaptive_optics.ipynb
  hcipy/atmosphere/__init__.py
  hcipy/atmosphere/standard_atmosphere.py
  tests/test_atmosphere.py
Labels: enhancement

#180 Fourier shift, shear and rotation operators.
  hcipy/fourier/__init__.py
  hcipy/fourier/fourier_operations.py
  tests/test_fourier.py
Labels: enhancement

#271 Use matplotlib transforms for `imshow_field()`
  doc/tutorial_notebooks/PyramidWFS/PyramidWFS.ipynb
  doc/tutorial_notebooks/VectorApodizingPhasePlate/VectorApodizingPhasePlate.ipynb
  doc/tutorial_notebooks/VortexCoronagraph/VortexCoronagraph.ipynb
  hcipy/plotting/field.py
  tests/test_plotting.py
Labels: enhancement, bugfix

#277 Add tests for grid utils and interpolators
  hcipy/field/util.py
  hcipy/interpolation/linear.py
  hcipy/interpolation/nearest.py
  tests/test_grid.py
  tests/test_interpolation.py
Labels: maintenance, bugfix

#281 fix grid dims and shape mixup.
  hcipy/plotting/field.py
Labels: bugfix

#261 Nan fix
  doc/team.rst
  hcipy/optics/surface_profiles.py
  tests/test_optics.py
Labels: enhancement

#282 Add new team members and update affiliations.
  doc/team.rst
Labels: documentation

#273 Improve the `ModalAdaptiveOpticsLayer` class
  hcipy/atmosphere/modal_adaptive_optics_layer.py
  tests/test_atmosphere.py
Labels: enhancement, documentation
